### PR TITLE
Explanation of John Tromp UNI machine

### PR DESCRIPTION
**Pull request by placek**

### CODE REVIEW

**Comment by melvinzhang** [comment]
Thanks for the contribution!

**Comment by melvinzhang** [comment]
@placek after prepossessing with gcc the output doesn't look right, I think gcc doesn't like multi-line define.
```
> gcc -E -x c -P uni_explained.lam
    (e (\exp1 bit1
      (cont (\args \arg exp1 (\p p arg args)))
      (e (\exp2 cont (\args (exp1 args) (exp2 args))))
    ))
    (bit1
      (cont (\args args bit1))
      (\list2 e (\var cont (\args var (args bit1))) list1)
    )
  )))
(\f ((\x x x) (\x f (x x)))) (\e \cont \list list (\bit0 \list1 list1 (\bit1 bit0 (\z z ((\x x x)(\x x x)))
```

**Comment by melvinzhang** [comment]
Fixed in https://github.com/melvinzhang/binary-lambda-calculus/commit/3893619e79c2b9413296fc17eeec39985fd65a10 by making the definition of E inline.

**Comment by placek** [comment]
I was using a custom preprocessor that somehow handles multiline `#define` - my bad.

I hope the main clue to understand the universal machine will be achieved anyway.

If you'll have questions about the John Tromp's implementation of `uni` I can explain it. It took me a while to understand it on my own and I know how unclear it is :)

In a future I plan to do such thing with inflate/deflate too.

**Pull request merged**
